<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-HMJQ3PC0" ignored="4" name="Default test(failed)(failed)" tests="2" failures="1" timestamp="2021-07-16T14:53:18 IST" time="0.075" errors="0">
  <testcase name="TC4" time="0.009" classname="testNG.testNG_failedxmlfile"/>
  <testcase name="TC2" time="0.004" classname="testNG.testNG_failedxmlfile">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNG.testNG_failedxmlfile.TC2(testNG_failedxmlfile.java:20)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC2 -->
  <testcase name="TC3" time="0.0" classname="testNG.testNG_failedxmlfile">
    <ignored/>
  </testcase> <!-- TC3 -->
  <testcase name="TC6" time="0.0" classname="testNG.testNG_failedxmlfile">
    <ignored/>
  </testcase> <!-- TC6 -->
  <testcase name="TC5" time="0.0" classname="testNG.testNG_failedxmlfile">
    <ignored/>
  </testcase> <!-- TC5 -->
  <testcase name="TC1" time="0.0" classname="testNG.testNG_failedxmlfile">
    <ignored/>
  </testcase> <!-- TC1 -->
</testsuite> <!-- Default test(failed)(failed) -->
